name: elearn
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  auto_animated: ^3.0.1
  flutter_staggered_animations: ^1.0.0
  ripple_animation: ^0.0.1+2
  animated_splash_screen: ^1.1.0
  flutter_spinkit: ^5.1.0
  animated_background: ^2.0.0
  pin_entry_text_field: ^0.1.4
  pin_entry_field: ^0.0.4
  flutter_svg: ^0.22.0
  http: ^0.13.3
  carousel_pro: ^1.0.0
  animated_widgets: ^1.1.0
  animator: ^3.1.0
  flutter_rating_bar: ^4.0.0
  video_player: ^2.2.7
  firebase_core: ^1.10.6
  firebase_analytics: ^9.0.4
   

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  #flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/EL.png
    - assets/down_arrow.png
    - assets/not_icon.png
    - assets/menu.png
    - assets/topics/t_1.png
    - assets/topics/t_2.png
    - assets/topics/t_3.png
    - assets/vedio_player_icon.png
    - assets/orange_circle.png
    - assets/main_bg.png
    - assets/bottom_left_bg.png
    - assets/top_right_bg.png
    - assets/transparent_book.png
    - assets/profile_bg.png
    - assets/dash_board/certification.png
    - assets/dash_board/courses.png
    - assets/dash_board/payment_his.png
    - assets/dash_board/quiz.png
    - assets/user_icon.png
    - assets/e_learning.png
    - assets/monitor.png
    - assets/ver_icon.png
    - assets/wrong.png
    - assets/double_tick.png
    - assets/VP_HELP.png
    - assets/VP_PAUSE.png
    - assets/VP_REPLAY.png
    - assets/icons/back.png
    - assets/icons/delete.png
    - assets/icons/download.png
    - assets/icons/edit.png
    
    
    - assets/drawer/Dashboard_icon.png
    - assets/drawer/Courses_icon.png
    - assets/drawer/Quizzes_icon.png
    - assets/drawer/Certification_icon.png
    - assets/drawer/PH_icon.png
    - assets/drawer/Settings_icon.png
    - assets/drawer/Privacy_icon.png
    - assets/drawer/logout.png
    - assets/drawer/feed_back.png
    - assets/drawer/topics.png
    



  fonts:
    - family: M_Light
      fonts:
        - asset: fonts/Montserrat_Light.ttf

    - family: M_Medium
      fonts:
        - asset: fonts/Montserrat_Medium.ttf    
        
    - family: M_Italic
      fonts:
        - asset: fonts/Montserrat_LightItalic.ttf  

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
